stewartmatheson/projectx

- src/TileMap.cpp
- src/main.cpp
Use the `texture_path` argument passed to `CreateTileMap`, and
update the call-site to match the expected asset path.
> Use `texture_path` argument

- headers/Editor.h
- headers/Room.h
- headers/TileMap.h
- src/Editor.cpp
- src/Room.cpp
- src/main.cpp
This covers moving the `struct`s to `class`es, where appropriate.
I've left both `Room` and `Tile` out of this, as `Tile` has no logic (hence all the members need to `public`) and similarly, all of `Room`'s members are accessed directly, so they would need to be marked `public` also, which kind of defeats the idea of making it a class.
Broken up into commits covering the migration of free functions to member methods, and the actual change from class to struct.
> C++ encapsulation

- headers/TileMap.h
- src/Editor.cpp
- src/Room.cpp
- src/TileMap.cpp
As the `scale` and `size` members of `TileMap` are very often
multiplied together in use, make a helper method to return that
> Add `TileMap::tileSize` method

- headers/RoomScene.h
- src/RoomScene.cpp
- src/main.cpp
Given that both the `Room` and `TileMap` instances will outlive
the `RoomScene` instance, these can be moved to references within
the `RoomScene` instance, which should perform as well as being
stored as pointers
> Move `Room` and `TileMap` to references

- src/Room.cpp
- src/RoomScene.cpp
Remove most of the uses of `this->` in the classes, the remainder
can be replaced through use of member initialiser lists
> Remove unecessary `this->` calls

- src/RoomScene.cpp
- src/TileMap.cpp
Mainly an aesthetic change, as the compiler is clever enough to
collapse them already, but move all initial assignments to direct
initialisations, e.g.:
foo f = foo(42);
becomes:
foo f(42);
> Initialise variables directly

- src/RoomScene.cpp
Use the `TileMap::tileSize` helper methods in more places where
`scale` * `size` is used directly
> Use `TileMap::tileSize` in more locations

- src/RoomScene.cpp
In the constructor for `RoomScene`, remove the default
initialisation of `last_mouse_position` as this will be done by
the compiler already
> Remove explicit default initialisation of value type

- src/RoomScene.cpp
- src/SpriteSheet.cpp
When constructing instances of `sf::RectangleShape` and
`sf::Sprite`, if we are immediately update members that can be
passed in via a constructor, use that constructor instead
> Use convenience constructors where possible

- src/Room.cpp
Now that `Room::bounds` is a value type, it will be initialised by
the time the `fstream` is read, so the values can be read directly
into the members (`left`, `top`, `width`, `height`)
> Read `Room` bounds information directly

- headers/Entity.h
- src/Entity.cpp
- src/RoomScene.cpp
To ensure that the player doesn't keep moving when editor has been
toggled, reset the movement vector via a `Reset` method on
`Entity`
This should take care of the situation where, in preview mode, while holding down a direction you can press `E` to get back into edit mode and the player sprite will continue moving.
> Add `Entity::Reset` to reset the movement vector

- src/HouseScene.cpp
- src/SpriteSheet.cpp
In `HouseScene::HouseScene(...)` remove unneeded default
construction of `last_mouse_position` and in
`SpriteSheet::SpriteSheet(...)` construct `tiles` directly and
push back each of the created sprites into it
> Clean up member variable initialisation

- src/House.cpp
When writing out the map to disk, iterate over the `tiles` member
field of `House` using a range-based for to remove boilerplate
> Iterate over `House::tiles` using range-based for

- CMakeLists.txt
To track down memory access issues, enable address sanitizer as
per:
https://clang.llvm.org/docs/AddressSanitizer.html
> Enable address sanitizer in Debug builds

- headers/TilePaletteView.h
- src/TilePaletteView.cpp
A couple of fixes that came up after running with the address sanitiser.
The first is to ensure that `TilePaletteView::selected_tile_index` is 0, which also ensures that the selection rectangle sits over the first palette tile item properly from the get go.
The second is to add a destructor on `TilePaletteView`, to ensure all the `new`ed up pointers are `delete`d
> Sanitizer fixups

- src/HouseScene.cpp
- src/TilePaletteView.cpp
Use some SFML method overloads that accept individual values instead of those that accept composite types (Vector2 etc) to avoid the assignment and clean up the code
> Sf convenience methods

- src/HouseScene.cpp
When initialising `house_view` as part of the `HouseScene`
constructor, use the `window_width` parameter instead of
accidentally using the `window_height` parameter twice
Fixes #34
> Use `window_width` when constructing `house_view`

- headers/Entity.h
- headers/HouseScene.h
- headers/Map.h
- headers/SpriteSheet.h
- headers/Tile.h
- headers/TilePaletteView.h
- src/Animation.cpp
- src/Entity.cpp
- src/HouseScene.cpp
- src/Map.cpp
- src/SpriteSheet.cpp
- src/TilePaletteView.cpp
- src/main.cpp
Added an entity system with map layers
1. Entities can now be both defined as well as added to the map
2. Entities have an entity type that will allow attaching different behavior in the future such as power ups and loot. 
3. Maps now have layers allowing sprites to sit on top of other sprites. Currently there is no way to select what layer you have active in the editor though
4. Used `std::for_each` after watching "No raw Loops". Awesome talk! Will start to try and refactor some other loops as I touch them. 
5. Extracted sprite sheet out of the `TilePaletteView`. I'd say that `SpriteSheet` still needs some cleanup however its a little more generic now.
> Map overhaul v2

- headers/HouseScene.h
- src/HouseScene.cpp
Update `HouseScene::Update` to accept the `current_mouse_position`
by reference, and to not copy-construct another `sf::Vector2i`
unnecessarily
> Update `current_mouse_position` handling

- src/Animation.cpp
Reset the animation frame counter at the last valid point, so each
frame will get the same amount of repeats (based on speed)
> Reset frame counter right at the end

- src/Entity.cpp
If there isn't an animation for the current animation key, return
early with the placeholder blank sprite
> Return early if animation not found

- src/HouseScene.cpp
For the remaining explicit construction of `std::unique_ptr`,
replace with `std::make_unique`, removing a few more `new`s
> Replace remaining explicit `std::unique_ptr` construction

- headers/Controller.h
- headers/EditorController.h
- headers/EventWithMouse.h
- headers/PlayerController.h
- src/EditorController.cpp
- src/PlayerController.cpp
Change function declarations to enforce `EventWithMouse` uses as
constant references
> Always use `EventWithMouse` instances as const ref

- src/EditorController.cpp
Fix a small issue with previous use of `getSize()` to get the
dimensions of the tile palette, which is now stored as a
`sf::IntRect`
> Use the `width` and `height` fields on `sf::IntRect`

- headers/ViewLayer.h
- src/ViewLayer.cpp
Move `ViewLayer::views` to `std::vector<std::unique_ptr<>>` and
update `ViewLayer::AddView` to both take an r-value, and ensure a
move into the `std::vector` with `std::move`. This matches all the
current call-sites, as they are all passed temporaries.
> Move `ViewLayer::views` to `std::unique_ptr`

- CMakeLists.txt
Add configuration item, defaulting to `-d` suffix, to allow
linking against plain SFML released libraries
> Allow linking against plain SFML

- src/PlayerController.cpp
The `numbers` header isn't being used, and is C++20 (which my
stock macOS compiler doesn't support) so I figure this can be
removed until needed
> Remove use of `numbers`

- CMakeLists.txt
- headers/GamepadControllerScheme.h
- headers/KeyboardControllerScheme.h
My understanding, pieced together from:
https://stackoverflow.com/questions/43282826/suppress-delete-non-virtual-dtor-warning-when-using-a-protected-non-virtual-dest
is that this can be an issue whenever a pointer of the base class is assigned an instance of the overriding class. In that case, the non-virtual destructor of the base class could be invoked (directly or via `delete`), not the destructor of the overriding
class.
Viz:
```
#include <cstdio>
#include <cstdlib>
struct Foo {
virtual void allocate(size_t count) = 0;
};
struct Bar : Foo {
void *buffer = nullptr;
void allocate(size_t count) override {
printf("Bar::allocate:  allocating buffer\n");
buffer = malloc(count);
}
~Bar() {
printf("Bar::~Bar:      freeing buffer\n");
free(buffer);
}
};
int main() {
Bar *bar_bar = new Bar(); …
```
> Debug warning fixes

- headers/Animation.h
- headers/AssetWatcher.h
When compiling with g++ 10.3.0, used of `std::atomic` and
`std::shared_ptr` need the appropriate headers
> Add include for `atomic` and `memory` headers

- CMakeLists.txt
Linux needs `pthread` to be linked in, so add a dependency on the
CMake `Threads` package to bring it in
> Determine and link against threading implementation

- src/AssetWatcher.cpp
Not actually tested, beyond mocking out with a win32 shim, but basically involves moving from `WaitForMultipleObjects` to `WaitForSingleObject` given that only one handle is being waited on.
> Asset watcher wait for single object

- CMakeLists.txt
- src/AssetWatcher.cpp
This moves from reading a hard coded asset path to one relative to the current working directory.
I had tested plugging a relative path directly into `FindFirstChangeNotification`, and that worked, but according to the [docs][1]:
> This cannot be a relative path or an empty string.
so I guess better safe than sorry 🤷🏻‍♂️ 
[1]: https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstchangenotificationa
> Asset watcher dynamic path

- headers/AssetWatcher.h
- src/AssetWatcher.cpp
Allow (semi)graceful termination of the `AssetWatcher` when shutting down.
This avoids the infinitely long wait when closing the main window.
> Asset watcher thread shutdown

- src/AssetWatcher.cpp
One change for the asset watcher was split across merges, this just puts it back to where it should be.
> Fix up merge issues

- src/AssetWatcher.cpp
This was dropped in the merges too.
5000ms is just a random figure I arrived at; basically it means that on shutdown you may have to wait up to 5 seconds before it will actually shutdown.
> Reinstate 5000ms timeout in watcher
